# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ashwath Bharadwaj
tagline:             'Musings of an Algorithm Enthusiast'
description:         'Musings of an Algorithm Enthusiast'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ashwath
  url:               ashwath10110.github.io
  email:             ashwath10110@gmail.com

# Custom vars
version:             1.0.0
